### ISSUE TITLE
Google Drive Links Unavailable

### ISSUE THREAD

**Issue by dpnde** [deep-man-yy/pepenude#7]
Google Drive Links have far too much traffic. Can you please upload them to alternative services like MEGA?

**Comment by deep-man-yy** [comment]
Yes, I will soon update with more links, in the meantime this may help:

https://www.geekrar.com/fix-bypass-google-drive-download-limit-error/

**Comment by MatthewHKnight** [comment]
I was going to compile it on Windows 7 for a friend but;

> C:\Users\Matthew\Desktop\easydeepnude-master\src\cli>C:\Users\Matthew\AppData\Lo
cal\Programs\Python\Python37-32\Scripts\pip.exe install -r requirements.txt
ERROR: torch-1.1.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform. 

If I can get a copy off Google drive i'll upload it to a few sites, would've been nice if a checksum would've been added to compare and make sure no idiot tried to inject a backdoor into it.

**Comment by wisp101** [comment]
@MatthewHKnight Your build failed because you are using a different python version. Torch is a c++ library with a python interface, so you need the right binary for your platform. You need to select the correct version from [here](https://pytorch.org/). I'd install the python dependencies manually and comment that line out of your install script.
